### ISSUE TITLE
Some bugs occur

### ISSUE THREAD

**Issue by seriousfreezing** [SashaKYotoz/Bedrockoid#2]
I know I could open several issues about it, but I'd rather summarize.
1. The sponges don't seem to work, or at least they don't seem to work if placed in the Desert, would the hot biomes only be in the Nether?
2. Pressing space to stop flying with Elytra doesn't seem to work, I've tried many times and nothing.
3. If you take the cauldron out of the water and put water in it, it stops being waterlogged.
4. The radius of the “Frostwalker” enchantment doesn't seem to work, as it's not a square around the player.
5. Should the plants be covered in snow by the player? I can't seem to do it.
6. I tried to join a vanilla server and it seems that the blocks around it are bugged. It looks like a similar case with mods like: SnowyLeavesPlus (in this case, I tried disabling all the features of your mod and it doesn't work).

I tested your mod on version 0.1-fabric-1.21.4 and with MidnightLib.

**Comment by SashaKYotoz** [comment]
1. They dry out not instantly like in nether, but by random tick
2. This is potentially bug
3. That's known bug and will be fixed in 0.1.1
4. It turned off for 1.21.1 and 1.21.4 because action of enchantment sets not in code, but json files of enchantment 
5. They haven't to, unless for now
6. Could you concretize what doesn't work in this case?

**Comment by seriousfreezing** [comment]
1. How long it takes to dry is nowhere explained.
4. So 1.21.4 won't have these versions?
6. It's a similar bug to this one, I don't know if it's for the same reason. But when you enter a server without your mod, it gets the blocks bugged like this. https://github.com/theRookieCoder/SnowyLeavesPlus/issues/2

**Comment by SashaKYotoz** [comment]
1. Mod was created within 2 weeks, so list of feature will be more clearer later this week
4. It will have, just it will handles in other way
6. Most likely it caused due to blockstate that changed by mod | if you could provide latest.log with this issue appeared it will so helpful

**Comment by seriousfreezing** [comment]
Sure! NP.
[latest.log](https://github.com/user-attachments/files/19228923/latest.log)

**Comment by SashaKYotoz** [comment]
in fact, latest.log doesn't have anything to help | fabric versions of mod were removed from modrinth and will be back once i'll be done with changing their code to avoid copyright ban from Wilder Wild

**Comment by seriousfreezing** [comment]
I'll wait then, but if you want to try to repeat this behavior, just use the Geyser test server, and log in using your mod.

**Comment by SashaKYotoz** [comment]
project once again is available on modrinth and mentioned bugs were fixed (testing on clean fabric server doesn't give an issue with blocks rendering, unless for my tests)

**Comment by seriousfreezing** [comment]
I tested it on the same server, only with Bedrockoid + Fabric API + ModMenu. I've disabled everything in the mod and the same block rendering problem remains.

**Comment by SashaKYotoz** [comment]
Could you provide screenshot or something how it looks like?

**Comment by seriousfreezing** [comment]
![Image](https://github.com/user-attachments/assets/96a30586-fbc1-498d-9a93-a1b98e7353cf)
![Image](https://github.com/user-attachments/assets/0932308c-5468-4d4b-a08b-c10d9d956bd8)
![Image](https://github.com/user-attachments/assets/46d64a5c-cff1-4622-903b-ae15ee225347)
![Image](https://github.com/user-attachments/assets/50180aa3-493b-48ec-bf7b-b112af0be62d)
I've restarted the game every time I reconfigure the mod and the effect is still there.

**Comment by SashaKYotoz** [comment]
And it's on Geyser test server, right? Could you try to switch off that options in file of config that have to be created in server folders as well, if it doesn't go right, are there any 'WARN' or 'ERROR' in log file?

**Comment by seriousfreezing** [comment]
I've tested all the features of the mod, and here's some new feedback:
1. The armor stand is always born with the wrong rotation and then adjusts, you can see it in a few frames. Will this be fixed?
2. The waterlogger bug is still there, I put water in it and it stops being waterlogged.
3. The elytra bug is still there too, I press the space button, hold it down and nothing happens.
4. The 2x2 fallen trees could be deactivated, since in Bedrock there is no such thing.
5. The Frostwalker lightning enchantment has not yet been implemented in Fabric, I've tested it and it's still as before.
6. I've created 2 worlds with all the features active and it doesn't seem to spawn the big mushrooms in the Swamp anymore.
7. It seems that flowers and grasses can be placed in the snow by the player! But it seems that the grasses spawn wrong, if it's tall grass it only spawns the top part of it and only the snow underneath.

**Comment by seriousfreezing** [comment]
> And it's on Geyser test server, right? Could you try to switch off that options in file of config that have to be created in server folders as well, if it doesn't go right, are there any 'WARN' or 'ERROR' in log file?
I've just joined Hypixel and the same thing happens. I don't own the Geyser test server, so I can't try to pull up the configuration file.

**Comment by SashaKYotoz** [comment]
![Image](https://github.com/user-attachments/assets/d476d60b-fca8-4824-a31f-afd31d1b4bbc)

just downloaded mod from modrinth (for test out of dev environment) and all (except 2x2 fallen tree config) listed errors don't exist and everything goes fine

**Comment by seriousfreezing** [comment]
If you want, I'll record a video, what do you think?
Maybe I tested it wrong, then

**Comment by SashaKYotoz** [comment]
it'll be useful

**Comment by seriousfreezing** [comment]
![Image](https://github.com/user-attachments/assets/da3421bb-50f1-4dad-b44d-6e451fbd0a14)
https://youtu.be/2o-oNH-NfLU
The giant mushrooms were born in the test video, which could indicate that it might just be a seed problem.

**Comment by SashaKYotoz** [comment]
Video is private, so could you change access type to 'available through link'?

**Comment by seriousfreezing** [comment]
Done.

**Comment by SashaKYotoz** [comment]
- i joined cubecraft and same problem works for me - bedrockoid is both client and server side, so if mod isn't on server this error is appeared

- i agree with you, cauldron isn't waterlogged if placed by player, the thing that was fixed - waterlogging when cauldron filled naturally

- pressing space when player is flying on elytra works, and there is 10 ticks limiter after player started fly

- plants seems to be self updated - it's bug and will fixed

- frostwalker enchantment was changed via json file of it in mod's data folder with increased 1 block more radius

**Comment by seriousfreezing** [comment]
1. I understand that it needs to be placed on the server side, I imagine that this could be the fault of the snow system in the leaves? Since many mods that try to do this fail and have this same problem. Except Visual Snowy Leaves, which manages to make it client-side only.
2. Hmmm, ok ok then this behavior will be fixed too, right?
3. All right, but during the whole flight I kept pressing and pressing the space button and not a moment went by.
4. Okay, but it's still not the same as Bedrock - which wasn't supposed to be circular but just a rectangle around the player.

**Comment by SashaKYotoz** [comment]
https://github.com/user-attachments/assets/00d398f2-958e-412b-ab43-f9af470f7c28

not to get offended:

thank you for the bugs you mentioned, they will be fixed

stop of the elytra works, as seen in the video

most likely, yes - the problem is in changing  blockstates and the server side, not on the client

**Comment by seriousfreezing** [comment]
> stop of the elytra works, as seen in the video

Can you tell me what the problem might be? Because all my attempts with elytra haven't worked.

> most likely, yes - the problem is in changing blockstates and the server side, not on the client

Would it be possible to disable this via configuration and play vanilla servers? Then there would be no conflict with your mod and vanilla servers.

**Comment by SashaKYotoz** [comment]
![Image](https://github.com/user-attachments/assets/49b0f841-f8d6-48fb-a19f-ef40a3cb37b3)

if you press space so frequently it resets timer to 0 each time

if you need client-side mod that adds Bedrock features, try [bedrockify](https://modrinth.com/mod/bedrockify), but most of features differ from bedrockoid

**Comment by seriousfreezing** [comment]
Okay, but will there be a fix for the vanilla servers? I'm currently thinking of adding your mod but with this blockstates bug it makes it totally unfeasible for modpacks with vanilla parity intent.

**Comment by SashaKYotoz** [comment]
Unless I have to remove all the additions of new block properties, it might work, but I don't even know, because it's kind of strange to add a mod created for the server and client side only as a client mod...

**Comment by seriousfreezing** [comment]
I see, I'll wait for a solution to this - so I can add it to my modpack.
